koinos/koinos-cli

- cmd/cli-wallet/interactive/interactive.go
- cmd/cli-wallet/main.go
- internal/wallet/commands.go
- internal/wallet/util.go
Ensures unicode support
Also add version information
Fix list order
Resolves #26
> Check terminal for unicode support

- internal/wallet/commands.go
- internal/wallet/interpreter.go
- internal/wallet/parser.go
My approach is to allow declare optional command parameters which will be set to empty string when parsing is done
Maybe we should create some const for this... don't know
> Balance command allow optional empty address when wallet is open #24

- .env
- CHANGELOG.md
- README.md
- internal/wallet/commands.go
- internal/wallet/errors.go
- internal/wallet/interpreter.go
- internal/wallet/parser.go
- internal/wallet/util.go
- internal/wallet/wallet_test.go
> Optional support / password env

- internal/wallet/interpreter.go
- internal/wallet/parser.go
- internal/wallet/wallet_test.go
> Fix metric crash

- internal/wallet/commands.go
Remove info, add info and private commands
Resolves #25
> Address / private commands

- README.md
- internal/cli/cli_test.go
- internal/cli/interpreter.go
- internal/cli/parser.go
- internal/util/errors.go
Various minor fixes in the parser and interpreter
> Parser fixes

- go.mod
- go.sum
- internal/cli/commands.go
- internal/cli/contract_commands.go
- internal/kjsonrpc/koinos_rpc_client.go
Submit and retrieve ABI to contract meta store
Resolves #11
> ABI manipulation

- internal/cli/commands.go
> Require ABI on upload

- ci/test.sh
- go.mod
- go.sum
- internal/cli/abi.go
- internal/cli/contract_commands.go
- internal/kjsonrpc/koinos_rpc_client.go
- internal/util/merkle_tree.go
- internal/util/merkle_tree_test.go
- internal/util/util.go
Bump proto version and handle new transaction creation method
Resolves https://github.com/koinos/koinos-proto/issues/67
> Bump proto

- internal/cli/abi.go
- internal/cli/abi_test.go
- internal/cli/contract_commands.go
Fixes various issues parsing types in ABI arguments
> Fix nested type handling

- internal/cli/commands.go
add arguments to the upload command in order to pass the "authorize overrides" options
> add authorize overrides to upload command

- internal/cli/abi.go
> Change ABI entry_point to entry-point

- cmd/cli/interactive/interactive.go
- go.mod
- go.sum
- internal/cli/abi.go
Resolves #44
Use custom for of go-prompt, which fixes the long-standing cursor issue
> Fix corruption

- cmd/cli/main.go
Resolves #126 
Show a warning when an rc file is missing
```
$ go run cmd/cli/main.go
rc file ".koinosrc" not found
Koinos CLI v0.4.0
Type "list" for a list of commands, "help <command>" for help on a specific command.
🚫 🔐 > 
```
> 126 rc crash

- CHANGELOG.md
- README.md
- internal/cli/commands.go
- internal/cliutil/util.go
> Bump version, change tKOIN to KOIN

- go.mod
- go.sum
> Update modules for 1.0.0

- .koinosrc
> Update .koinosrc for mainnet pob and vhp

- README.md
This is just an update to the README file to specify https for the endpoint
> Change endpoint in readme to be https

- go.mod
- go.sum
Bump go-prompt to remove console warning message.
Resolves #166 
Get rid of warning message when pasting a large string
> Involves #166

- internal/cli/token_commands.go
Fix balance check on token transfer
Resolves #170
> Fix balance check on token transfer

- internal/cli/contract_commands.go
- internal/cli/token_commands.go
Resolves #169
Enables offline signing for transactions containing contract calls
> Allow offline signing for contract calls

- internal/cliutil/util.go
> Bump version number to v2.0.0

- .koinosrc
Updates the VHP contract in the `.koinosrc` file.
> Update the VHP address in the RC file
